apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-macos
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: mybucket
      tlsSkipVerify: true
    secureJsonData:
      token: mytoken123
    isDefault: true
    editable: false
